package com.yzit.plateform.entity;
import com.yzit.core.base.BaseEntity;
 /**
 * <b>功能:</b>登录用户实体类<br>
 * <b>作者:</b>Administrator<br>
 * <b>日期:</b>Tue Jan 02 10:21:30 CST 2018 <br>
 * <b>版权所有:云优众<br>
 */
public class User extends BaseEntity {
   	private static final long serialVersionUID = 1L;
		private Integer id;//编号	private Integer organId;//归属部门	private String loginName;//登录名	private String pwd;//密码	private String staffNo;//工号	private String name;//姓名	private String email;//邮箱	private String phone;//电话	private String mobile;//手机	private String userType;//用户类型	private String photo;//用户头像	private String loginIp;//最后登陆IP	private java.util.Date loginDate;//最后登陆时间	private Integer loginFlag;//是否可登录	private String remarks;//备注信息	private String delFlag;//删除标记	public Integer getId() {	    return this.id;	}	public void setId(Integer id) {	    this.id=id;	}	public Integer getOrganId() {	    return this.organId;	}	public void setOrganId(Integer organId) {	    this.organId=organId;	}	public String getLoginName() {	    return this.loginName;	}	public void setLoginName(String loginName) {	    this.loginName=loginName;	}	public String getPwd() {	    return this.pwd;	}	public void setPwd(String pwd) {	    this.pwd=pwd;	}	public String getStaffNo() {	    return this.staffNo;	}	public void setStaffNo(String staffNo) {	    this.staffNo=staffNo;	}	public String getName() {	    return this.name;	}	public void setName(String name) {	    this.name=name;	}	public String getEmail() {	    return this.email;	}	public void setEmail(String email) {	    this.email=email;	}	public String getPhone() {	    return this.phone;	}	public void setPhone(String phone) {	    this.phone=phone;	}	public String getMobile() {	    return this.mobile;	}	public void setMobile(String mobile) {	    this.mobile=mobile;	}	public String getUserType() {	    return this.userType;	}	public void setUserType(String userType) {	    this.userType=userType;	}	public String getPhoto() {	    return this.photo;	}	public void setPhoto(String photo) {	    this.photo=photo;	}	public String getLoginIp() {	    return this.loginIp;	}	public void setLoginIp(String loginIp) {	    this.loginIp=loginIp;	}	public java.util.Date getLoginDate() {	    return this.loginDate;	}	public void setLoginDate(java.util.Date loginDate) {	    this.loginDate=loginDate;	}	public Integer getLoginFlag() {	    return this.loginFlag;	}	public void setLoginFlag(Integer loginFlag) {	    this.loginFlag=loginFlag;	}	public String getRemarks() {	    return this.remarks;	}	public void setRemarks(String remarks) {	    this.remarks=remarks;	}	public String getDelFlag() {	    return this.delFlag;	}	public void setDelFlag(String delFlag) {	    this.delFlag=delFlag;	}
}

